server:  
  port: ${PORT:3333}

spring:  
  application:
    name: customer-service

#eureka:  
#  client:
#    serviceUrl:
#      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
      
#ribbon:
#  eureka:
#    enabled: true