spring.application.name: customer-service-grpc
spring.output.ansi.enabled: always

management.endpoints.web.exposure.include: metrics
management.endpoint.metrics.enabled: true

server.port: 8081
spring.grpc.server.port: 9091

spring.grpc.client.channels.local.address: localhost:9090